// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using o2rabbit.Migrations.Context;

#nullable disable

namespace o2rabbit.Migrations.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20250326103511_FixTypeInColumn")]
    partial class FixTypeInColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("o2rabbit.Core.Entities.Mappings.ProcessProcessMapping", b =>
                {
                    b.Property<long>("ChildId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("ChildId", "ParentId");

                    b.HasIndex("ParentId");

                    b.ToTable("ProcessProcessMapping");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Mappings.ProcessSpaceMapping", b =>
                {
                    b.Property<long>("ProcessId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint");

                    b.HasKey("ProcessId", "SpaceId");

                    b.HasIndex("SpaceId");

                    b.ToTable("ProcessSpaceMapping");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Process", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Processes", (string)null);
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.ProcessComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("ProcessComments", (string)null);
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Space", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Spaces", (string)null);
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.SpaceComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.ToTable("SpaceComments", (string)null);
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Statuses", (string)null);
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.StatusTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ToStatusId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("StatusTransitions", (string)null);
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("SpaceId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.TicketComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComments", (string)null);
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Workflow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProcessId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId")
                        .IsUnique();

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Mappings.ProcessProcessMapping", b =>
                {
                    b.HasOne("o2rabbit.Core.Entities.Process", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("o2rabbit.Core.Entities.Process", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Mappings.ProcessSpaceMapping", b =>
                {
                    b.HasOne("o2rabbit.Core.Entities.Process", null)
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("o2rabbit.Core.Entities.Space", null)
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.ProcessComment", b =>
                {
                    b.HasOne("o2rabbit.Core.Entities.Process", "Process")
                        .WithMany("Comments")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Process");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.SpaceComment", b =>
                {
                    b.HasOne("o2rabbit.Core.Entities.Space", "Space")
                        .WithMany("Comments")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Space");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Status", b =>
                {
                    b.HasOne("o2rabbit.Core.Entities.Workflow", "Workflow")
                        .WithMany("Statuses")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.StatusTransition", b =>
                {
                    b.HasOne("o2rabbit.Core.Entities.Status", "FromStatus")
                        .WithMany("FromTransitions")
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("o2rabbit.Core.Entities.Status", "ToStatus")
                        .WithMany("ToTransitions")
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Ticket", b =>
                {
                    b.HasOne("o2rabbit.Core.Entities.Ticket", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("o2rabbit.Core.Entities.Process", "Process")
                        .WithMany("Tickets")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("o2rabbit.Core.Entities.Space", "Space")
                        .WithMany("AttachedTickets")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Process");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.TicketComment", b =>
                {
                    b.HasOne("o2rabbit.Core.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Workflow", b =>
                {
                    b.HasOne("o2rabbit.Core.Entities.Process", "Process")
                        .WithOne("Workflow")
                        .HasForeignKey("o2rabbit.Core.Entities.Workflow", "ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Process", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Tickets");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Space", b =>
                {
                    b.Navigation("AttachedTickets");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Status", b =>
                {
                    b.Navigation("FromTransitions");

                    b.Navigation("ToTransitions");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Ticket", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("o2rabbit.Core.Entities.Workflow", b =>
                {
                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
